install:
    npm install

serve:
    npm run serve

build:
    npm run build

test-unit:
    npm run test:unit

test-e2e:
    npm run test:e2e

lint:
    npm run lint

terraform-apply:
    terraform apply

terraform-apply-lambda-only:
    terraform apply -target=module.lambda

# Build locally prod mode with docker 
docker-build:
    docker build -t it-vibe-static-site:1.0 .

docker-run:
    docker run -d -p 8080:80 it-vibe-static-site:1.0


# Lambda
zip_get_companies_lambda:
    zip -r get_companies.zip get_companies.py

zip_save_company_lambda:
    zip -r save_company.zip save_company.py