openapi: 3.0.0
info:
  title: ITVibe API
  version: 1.0.0
  description: API for managing companies

paths:

  /companies:
    get:
      x-amazon-apigateway-integration:
        uri: "${get_compagnies_lambda_invoke_arn}"
        httpMethod: POST
        type: aws_proxy
      summary: Get all companies
      responses:
        "200":
          description: A list of companies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Company"
    
components:
  schemas:
    Company:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        address:
          type: string
        phone:
          type: string
        email:
          type: string
        size:
          type: number
        createdAt:
          type: string
          format: date-time
        siren:
          type: string
        siret:
          type: string
        capital:
          type: number
        legalForm:
          type: string
        activity:
          type: string
        vatNumber:
          type: string
        website:
          type: string
        logo:
          type: string
        description:
          type: string
        socialNetworks:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              url:
                type: string
