openapi: 3.0.0
info:
  title: ITVibe API
  version: 1.0.0
  description: API for managing companies

paths:
  /healthcheck:
    get:
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: '{"statusCode": 200}'
        responses:
          default:
            statusCode: "200"
            responseTemplates:
              application/json: '{"status": "healthy"}'
      summary: Health check
      responses:
        "200":
          description: Health check successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /companies:
    get:
      x-amazon-apigateway-integration:
        uri: "${get_companies_lambda_invoke_arn}"
        httpMethod: POST
        type: aws_proxy
      summary: List all companies
      responses:
        "200":
          description: A list of companies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Company"
    post:
      x-amazon-apigateway-integration:
        uri: "${create_company_lambda_invoke_arn}"
        httpMethod: POST
        type: aws_proxy
      summary: Create a company
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Company"
      responses:
        "201":
          description: The created company
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Company"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Company:
      type: object
      properties:
        id:
          type: string
          example: "aefb1b1b-1b1b-1b1b-1b1b-1b1b1b1b1b1b"
        name:
          type: string
          example: "ITVibe"
        location:
          type: string
          example: "Paris"
        size:
          type: number
          example: 100
        revenue:
          type: number
          example: 1000000
        industry:
          type: string
          example: "IT"
        description:
          type: string
          example: "IT company"

    Error:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer
