name: Build deploy Main

on:
  push:
    branches:
      - main

jobs:
# Build jobs: build-front-end, build-back-end
  build-front-end:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        working-directory: it-vibe-fe
        run: npm install

      - name: Run build
        working-directory: it-vibe-fe
        run: npm run build -- --mode dev

      - name: Archive static web-site artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: it-vibe-fe/dist
  build-back-end:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

# Deploy jobs: deploy-front-end, deploy-back-end
  deploy:
    runs-on: ubuntu-latest
    needs: [build-front-end, build-back-end]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download static web-site artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: it-vibe-fe/dist


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init
    
      - name: Select terraform workspace
        working-directory: terraform
        run: terraform workspace select dev

      - name: Apply Terraform configuration
        working-directory: terraform
        run: terraform apply -auto-approve -var "be_version=latest" -var "env=dev"
