name: Build deploy version

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        type: choice
        options:
          - stg
          - preprod
          - prod

jobs:
  infos:
    if: startsWith(github.ref, 'refs/tags/') # Ensure the job runs only on tags
    runs-on: ubuntu-latest
    steps:
      - name: Job info
        run: |
          echo "Running Deploy version job..."
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Tag: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
          echo "Repository: ${{ github.repository }}"       
      - name: Checkout repository
        uses: actions/checkout@v3
  build-front-end:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        working-directory: it-vibe-fe
        run: npm install

      - name: Run build
        working-directory: it-vibe-fe
        run: npm run build -- --mode ${{ github.event.inputs.environment }}

      - name: Archive static web-site artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: it-vibe-fe/dist